### PR TITLE
Fix check for /.dockerenv

### LINKED ISSUE #9: .dockerinit should be replaced with .dockerenv
This is giving false alarm when using Docker version 1.11.0: https://github.com/hypriot/image-builder-odroid-c2/blob/f999bbdbb0de39e2b60eb6fdac4c8e2eccf67343/builder/build.sh#L5

### PR DESCRIPTION
**Pull request by StefanScherer**
Check for /.dockerenv instead of ./dockerinit

Fixes #9

### CODE REVIEW

File: builder/chroot-script.sh [hunk 1]
```diff
@@ -47,7 +47,7 @@ apt-get install -y u-boot-tools initramfs-tools
 
 # make the kernel package create a copy of the current kernel here
 touch /boot/uImage
-apt-get install -y linux-image-c2 bootini
+apt-get install -y linux-image-c2 bootini --no-install-recommends
```
Comment (StefanScherer) [inline builder/chroot-script.sh]: Add suggestion #13
